openstack:
  build: ../openstack-node-containers/all-openstack-docker/docker-files/kilo/controller/
  hostname: openstack
  container_name: openstack
  environment:
    MYSQL_ROOT_PASSWORD: c0ntrail123
    RABBIT_PASS: c0ntrail123
    KEYSTONE_DBPASS: c0ntrail123
    GLANCE_DBPASS: c0ntrail123
    NOVA_DBPASS: c0ntrail123
    CINDER_DBPASS: c0ntrail123
    HEAT_DBPASS: c0ntrail123
    KEYSTONE_PASS: c0ntrail123
    GLANCE_PASS: c0ntrail123
    NOVA_PASS: c0ntrail123
    NEUTRON_PASS: c0ntrail123
    CINDER_PASS: c0ntrail123
    HEAT_PASS: c0ntrail123
    ADMIN_TENANT_NAME: admin
    ADMIN_TOKEN: c0ntrail123
    ADMIN_PASS: c0ntrail123
    DEMO_PASS: c0ntrail123
    REGION_NAME: RegionOne
